services:
  unifi-controller:
    container_name: unifi-controller
    image: jacobalberty/unifi
    restart: always
    volumes:
      - ./unifi:/unifi
    ports:
      - 8080:8080/tcp
      - 8443:8443/tcp
      - 3478:3478/udp
      - 8843:8843/tcp
      - 8880:8880/tcp
      - 6789:6789/tcp
    environment:
      - TZ=Europe/London
